### PR TITLE
Use go.pantheon.tech

### PR DESCRIPTION
**Pull request by mmiklus**
Signed-off-by: Miroslav Miklus <miroslav.miklus@pantheon.tech>

### CODE REVIEW

**Comment by mmiklus** [comment]
@pt-maros - please review

**Review by pt-maros — APPROVED** [review]
It builds, it installs, it runs.

**Comment by ondrej-fabry** [comment]
:warning: Note that the vpptop has not been added to the [go.pantheon.tech site repo](https://github.com/PANTHEONtech/go.pantheon.tech) yet. 
So `go.pantheon.tech/vpptop` will not resolve for go tools:

```
➤ curl https://go.pantheon.tech/vpptop\?go-get\=1
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-us">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
</head>
<body>
  <h1>Page Not Found</h1>
  <p>Sorry, but the page you were trying to view does not exist.</p>
</body>
</html>
```

**Comment by mmiklus** [comment]
https://github.com/PANTHEONtech/go.pantheon.tech/blob/main/vpptop.html
https://go.pantheon.tech/vpptop

**Review by ondrej-fabry — APPROVED** [review]

**Pull request merged**
